import type { Metadata } from "next";
import { Recursive } from "next/font/google";
import "../globals.css";
import { cn } from "@/lib/utils";
import { hasLocale, NextIntlClientProvider } from "next-intl";
import { routing } from "@/i18n/routing";
import { notFound } from "next/navigation";
import { SidebarProvider, SidebarTrigger } from "@/components/ui/sidebar";
import { AppSidebar } from "@/components/app-sidebar";
import { TooltipProvider } from "@/components/ui/tooltip";
import { AppBreadcrumb } from "@/components/app-breadcrumb";

type Props = {
  children: React.ReactNode;
  params: Promise<{ locale: string }>;
};

const inter = Recursive({
  subsets: ["latin"],
  variable: "--font-sans",
});


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({ children, params }: Props) {
  const { locale } = await params;
  if (!hasLocale(routing.locales, locale)) {
    notFound();
  }
  const messages = (await import(`../../messages/${locale}.json`)).default;

  return (
    <html
      className={cn(
        "h-full",
        "antialiased",
        "font-sans",
        inter.variable
      )}
    >
      <TooltipProvider>
        <body className="min-h-full flex flex-col">
          <SidebarProvider>
            <AppSidebar />

            <div className="w-full h-dvh relative">
              <nav className="flex w-full items-center gap-4 fixed top-0 p-2 bg-sidebar border-b backdrop-blur-sm">
                <SidebarTrigger />
                <AppBreadcrumb />
              </nav>
            
              {children}
            </div>

          </SidebarProvider>
        </body>
      </TooltipProvider>
    </html >
  );
}