import type { Metadata } from "next";
import { Roboto } from "next/font/google";
import "../globals.css";
import { cn } from "@/lib/utils";
import { hasLocale, NextIntlClientProvider } from "next-intl";
import { routing } from "@/i18n/routing";
import { notFound } from "next/navigation";
import { SidebarProvider, SidebarTrigger } from "@/components/ui/sidebar";
import { AppSidebar } from "@/components/app-sidebar";
import { TooltipProvider } from "@/components/ui/tooltip";
import { AppBreadcrumb } from "@/components/app-breadcrumb";
import ReactQueryProvider from "@/providers/react-query-provider";
import { Toaster } from "@/components/ui/sonner";
import { ThemeProvider as NextThemesProvider } from "next-themes";

type Props = {
  children: React.ReactNode;
  params: Promise<{ locale: string }>;
};

const inter = Roboto({
  subsets: ["latin"],
  variable: "--font-sans",
});


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({ children, params }: Props) {
  const { locale } = await params;
  if (!hasLocale(routing.locales, locale)) {
    notFound();
  }
  const messages = (await import(`../../messages/${locale}.json`)).default;

  return (
    <html
      className={cn(
        "h-full",
        "antialiased",
        "font-sans",
        inter.variable
      )}
      suppressHydrationWarning
    >
      <ReactQueryProvider>
        <NextThemesProvider
            attribute="class"
            defaultTheme="system"
            enableSystem
          >
        <TooltipProvider>
          <body className="min-h-full flex flex-col">
            <NextIntlClientProvider locale={locale} messages={messages}>
              <SidebarProvider>
                <AppSidebar />

                <div className="w-full h-dvh relative">
                  <nav className="flex w-full items-center gap-4 sticky top-0 p-2 bg-sidebar z-50 border-b">
                    <SidebarTrigger />
                    <AppBreadcrumb />
                  </nav>
                  <div className="px-4 h-full py-4" >
                    {children}
                    <Toaster />
                  </div>
                </div>

              </SidebarProvider>
            </NextIntlClientProvider>
          </body>
        </TooltipProvider>
        </NextThemesProvider>
      </ReactQueryProvider>
    </html >
  );
}